# permissions for end users to view acls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acl-viewer-role
rules:
- apiGroups:
  - cache.extensions.tsuru.io
  resources:
  - acls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.extensions.tsuru.io
  resources:
  - acls/status
  verbs:
  - get
