# permissions for end users to view ACLDNSEntrys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ACLDNSEntry-viewer-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - ACLDNSEntrys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - ACLDNSEntrys/status
  verbs:
  - get
