# permissions for end users to edit ACLDNSEntrys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ACLDNSEntry-editor-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - ACLDNSEntrys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - ACLDNSEntrys/status
  verbs:
  - get
