---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.extensions.tsuru.io
  resources:
  - acls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.extensions.tsuru.io
  resources:
  - acls/finalizers
  verbs:
  - update
- apiGroups:
  - cache.extensions.tsuru.io
  resources:
  - acls/status
  verbs:
  - get
  - patch
  - update
