---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - ACLDNSEntrys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - ACLDNSEntrys/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - ACLDNSEntrys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - acls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - acls/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - acls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstanceaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstanceaddresses/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstanceaddresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappaddresses/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappaddresses/status
  verbs:
  - get
  - patch
  - update
