---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - ACLDNSEntrys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - ACLDNSEntrys/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - ACLDNSEntrys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - acls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - acls/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - acls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstanceadresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstanceadresses/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstanceadresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappadresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappadresses/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappadresses/status
  verbs:
  - get
  - patch
  - update
