# permissions for end users to edit rpaasinstanceaddresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rpaasinstanceaddress-editor-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstanceaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstanceaddresses/status
  verbs:
  - get
