# permissions for end users to view rpaasinstanceaddresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rpaasinstanceaddress-viewer-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstanceaddresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstanceaddresses/status
  verbs:
  - get
