# permissions for end users to edit tsuruappadresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsuruappadress-editor-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappadresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappadresses/status
  verbs:
  - get
