# permissions for end users to edit tsuruappaddresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsuruappaddress-editor-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappaddresses/status
  verbs:
  - get
