# permissions for end users to view tsuruappaddresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsuruappaddress-viewer-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappaddresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - tsuruappaddresses/status
  verbs:
  - get
