apiVersion: extensions.tsuru.io/v1alpha1
kind: ACL
metadata:
  name: paulo-teste
  namespace: tsuru-gke-main
spec:
  source:
    tsuruApp: paulo-teste
  destinations:
  - externalDNS:
      name: www.google.com
      ports:
      - protocol: tcp
        number: 80
      - protocol: tcp
        number: 443
