# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/extensions.tsuru.io_acls.yaml
- bases/extensions.tsuru.io_acldnsentries.yaml
- bases/extensions.tsuru.io_tsuruappaddresses.yaml
- bases/extensions.tsuru.io_rpaasinstanceaddresses.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_acls.yaml
#- patches/webhook_in_ACLDNSEntrys.yaml
#- patches/webhook_in_tsuruappaddresses.yaml
#- patches/webhook_in_rpaasinstanceaddresses.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_acls.yaml
#- patches/cainjection_in_ACLDNSEntrys.yaml
#- patches/cainjection_in_tsuruappaddresses.yaml
#- patches/cainjection_in_rpaasinstanceaddresses.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml

# Remove OpenAPI validation due to errors while creating the CRDs.
patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: .*
  patch: |-
    - op: replace
      value: {}
      path: /spec/versions/0/schema/openAPIV3Schema/properties

    - op: add
      path: /spec/versions/0/schema/openAPIV3Schema/x-kubernetes-preserve-unknown-fields
      value: true
